### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by Guseyn**
regarding to #4

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#13](https://github.com/artipie/vertx-server/issues/13) is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f7f00117-78f0-46e6-8b73-fb3de441387a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by HDouss** [comment]
@g4s8 looks good. Please review or merge.

**Review by HDouss — APPROVED** [review]

**Review by HDouss — APPROVED** [review]

**Comment by HDouss** [comment]
@0crat status

**Comment by HDouss** [comment]
@g4s8 how to trigger rewards here?

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by g4s8** [comment]
@sereshqua can you comment here now?

**Comment by HDouss** [comment]
@sereshqua Could you please make the review?

**Comment by g4s8** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
