### PR TITLE
Upgraded HTTP to 0.8.2

### LINKED ISSUE #15: Not compatible with HTTP 0.8.2
Some interfaces were changed in HTTP, now Vert.x implementation for HTTP is not compatible with latest HTTP release

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #15

### CODE REVIEW

**Comment by olegmoz** [comment]
@g4s8 could you please merge this in and release, please?

**Comment by g4s8** [comment]
@olegmoz merged, please check release progress here: https://github.com/artipie/vertx-server/issues/15#issuecomment-618304676

**Comment by olegmoz** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by 0crat** [comment]
Job `gh:artipie/vertx-server#16` is not assigned, can't get performer

**Pull request merged**
